AnimationPointers:
	dw BulbasaurAnimation
	dw IvysaurAnimation
	dw VenusaurAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw CaterpieAnimation
	dw MetapodAnimation
	dw ButterfreeAnimation
	dw WeedleAnimation
	dw KakunaAnimation
	dw BeedrillAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw RattataAnimation
	dw RaticateAnimation
	dw SpearowAnimation
	dw FearowAnimation
	dw EkansAnimation
	dw ArbokAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw SandshrewAnimation
	dw SandslashAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw VulpixAnimation
	dw NinetalesAnimation
	dw JigglypuffAnimation
	dw WigglytuffAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw OddishAnimation
	dw GloomAnimation
	dw VileplumeAnimation
	dw ParasAnimation
	dw ParasectAnimation
	dw VenonatAnimation
	dw VenomothAnimation
	dw DiglettAnimation
	dw DugtrioAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw PsyduckAnimation
	dw GolduckAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw PoliwagAnimation
	dw PoliwhirlAnimation
	dw PoliwrathAnimation
	dw AbraAnimation
	dw KadabraAnimation
	dw AlakazamAnimation
	dw MachopAnimation
	dw MachokeAnimation
	dw MachampAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw GeodudeAnimation
	dw GravelerAnimation
	dw GolemAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw FarfetchDAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw ShellderAnimation
	dw CloysterAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw KrabbyAnimation
	dw KinglerAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ExeggcuteAnimation
	dw ExeggutorAnimation
	dw CuboneAnimation
	dw MarowakAnimation
	dw HitmonleeAnimation
	dw HitmonchanAnimation
	dw LickitungAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw KangaskhanAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw GoldeenAnimation
	dw SeakingAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MrMimeAnimation
	dw ScytherAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw MagmarAnimation
	dw PinsirAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw VaporeonAnimation
	dw JolteonAnimation
	dw FlareonAnimation
	dw PorygonAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw KabutoAnimation
	dw KabutopsAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw DratiniAnimation
	dw DragonairAnimation
	dw DragoniteAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw SentretAnimation
	dw FurretAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw LedybaAnimation
	dw LedianAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw PichuAnimation
	dw CleffaAnimation
	dw IgglybuffAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw BellossomAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw PolitoedAnimation
	dw HoppipAnimation
	dw SkiploomAnimation
	dw JumpluffAnimation
	dw AipomAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw EspeonAnimation
	dw UmbreonAnimation
	dw MurkrowAnimation
	dw SlowkingAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw WobbuffetAnimation
	dw GirafarigAnimation
	dw PinecoAnimation
	dw ForretressAnimation
	dw DunsparceAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw QwilfishAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw SlugmaAnimation
	dw MagcargoAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw TyrogueAnimation
	dw HitmontopAnimation
	dw SmoochumAnimation
	dw ElekidAnimation
	dw MagbyAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw TreeckoAnimation
	dw GrovyleAnimation
	dw SceptileAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw MudkipAnimation
	dw MarshtompAnimation
	dw SwampertAnimation
	dw PoochyenaAnimation
	dw MightyenaAnimation
	dw ZigzagoonAnimation
	dw LinooneAnimation
	dw WurmpleAnimation
	dw SilcoonAnimation
	dw BeautiflyAnimation
	dw CascoonAnimation
	dw DustoxAnimation
	dw LotadAnimation
	dw LombreAnimation
	dw LudicoloAnimation
	dw SeedotAnimation
	dw NuzleafAnimation
	dw ShiftryAnimation
	dw TaillowAnimation
	dw SwellowAnimation
	dw WingullAnimation
	dw PelipperAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw SurskitAnimation
	dw MasquerainAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw SlakothAnimation
	dw VigorothAnimation
	dw SlakingAnimation
	dw NincadaAnimation
	dw NinjaskAnimation
	dw ShedinjaAnimation
	dw WhismurAnimation
	dw LoudredAnimation
	dw ExploudAnimation
	dw MakuhitaAnimation
	dw HariyamaAnimation
	dw AzurillAnimation
	dw NosepassAnimation
	dw SkittyAnimation
	dw DelcattyAnimation
	dw SableyeAnimation
	dw MawileAnimation
	dw AronAnimation
	dw LaironAnimation
	dw AggronAnimation
	dw MedititeAnimation
	dw MedichamAnimation
	dw ElectrikeAnimation
	dw ManectricAnimation
	dw PlusleAnimation
	dw MinunAnimation
	dw VolbeatAnimation
	dw IllumiseAnimation
	dw RoseliaAnimation
	dw GulpinAnimation
	dw SwalotAnimation
	dw CarvanhaAnimation
	dw SharpedoAnimation
	dw WailmerAnimation
	dw WailordAnimation
	dw NumelAnimation
	dw CameruptAnimation
	dw TorkoalAnimation
	dw SpoinkAnimation
	dw GrumpigAnimation
	dw SpindaAnimation
	dw TrapinchAnimation
	dw VibravaAnimation
	dw FlygonAnimation
	dw CacneaAnimation
	dw CacturneAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw ZangooseAnimation
	dw SeviperAnimation
	dw LunatoneAnimation
	dw SolrockAnimation
	dw BarboachAnimation
	dw WhiscashAnimation
	dw CorphishAnimation
	dw CrawdauntAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw LileepAnimation
	dw CradilyAnimation
	dw AnorithAnimation
	dw ArmaldoAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw CastformAnimation
	dw KecleonAnimation
	dw ShuppetAnimation
	dw BanetteAnimation
	dw DuskullAnimation
	dw DusclopsAnimation
	dw TropiusAnimation
	dw ChimechoAnimation
	dw AbsolAnimation
	dw WynautAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw SphealAnimation
	dw SealeoAnimation
	dw WalreinAnimation
	dw ClamperlAnimation
	dw HuntailAnimation
	dw GorebyssAnimation
	dw RelicanthAnimation
	dw LuvdiscAnimation
	dw BagonAnimation
	dw ShelgonAnimation
	dw SalamenceAnimation
	dw BeldumAnimation
	dw MetangAnimation
	dw MetagrossAnimation
	dw RegirockAnimation
	dw RegiceAnimation
	dw RegisteelAnimation
	dw LatiasAnimation
	dw LatiosAnimation
	dw KyogreAnimation
	dw GroudonAnimation
	dw RayquazaAnimation
	dw JirachiAnimation
	dw DeoxysAnimation
	dw TurtwigAnimation
	dw GrotleAnimation
	dw TorterraAnimation
	dw ChimcharAnimation
	dw MonfernoAnimation
	dw InfernapeAnimation
	dw PiplupAnimation
	dw PrinplupAnimation
	dw EmpoleonAnimation
	dw StarlyAnimation
	dw StaraviaAnimation
	dw StaraptorAnimation
	dw BidoofAnimation
	dw BibarelAnimation
	dw KricketotAnimation
	dw KricketuneAnimation
	dw ShinxAnimation
	dw LuxioAnimation
	dw LuxrayAnimation
	dw BudewAnimation
	dw RoseradeAnimation
	dw CranidosAnimation
	dw RampardosAnimation
	dw ShieldonAnimation
	dw BastiodonAnimation
	dw BurmyAnimation
	dw WormadamAnimation
	dw MothimAnimation
	dw CombeeAnimation
	dw VespiquenAnimation
	dw PachirisuAnimation
	dw BuizelAnimation
	dw FloatzelAnimation
	dw CherubiAnimation
	dw CherrimAnimation
	dw ShellosAnimation
	dw GastrodonAnimation
	dw AmbipomAnimation
	dw DrifloonAnimation
	dw DrifblimAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw MismagiusAnimation
	dw HonchkrowAnimation
	dw GlameowAnimation
	dw PuruglyAnimation
	dw ChinglingAnimation
	dw StunkyAnimation
	dw SkuntankAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw BonslyAnimation
	dw MimeJrAnimation
	dw HappinyAnimation
	dw ChatotAnimation
	dw SpiritombAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw MunchlaxAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw HippopotasAnimation
	dw HippowdonAnimation
	dw SkorupiAnimation
	dw DrapionAnimation
	dw CroagunkAnimation
	dw ToxicroakAnimation
	dw CarnivineAnimation
	dw FinneonAnimation
	dw LumineonAnimation
	dw MantykeAnimation
	dw SnoverAnimation
	dw AbomasnowAnimation
	dw WeavileAnimation
	dw MagnezoneAnimation
	dw LickilickyAnimation
	dw RhyperiorAnimation
	dw TangrowthAnimation
	dw ElectivireAnimation
	dw MagmortarAnimation
	dw TogekissAnimation
	dw YanmegaAnimation
	dw LeafeonAnimation
	dw GlaceonAnimation
	dw GliscorAnimation
	dw MamoswineAnimation
	dw PorygonZAnimation
	dw GalladeAnimation
	dw ProbopassAnimation
	dw DusknoirAnimation
	dw FroslassAnimation
	dw RotomAnimation
	dw UxieAnimation
	dw MespritAnimation
	dw AzelfAnimation
	dw DialgaAnimation
	dw PalkiaAnimation
	dw HeatranAnimation
	dw RegigigasAnimation
	dw GiratinaAnimation
	dw CresseliaAnimation
	dw PhioneAnimation
	dw ManaphyAnimation
	dw DarkraiAnimation
	dw ShayminAnimation
	dw ArceusAnimation
	dw SylveonAnimation
	dw RegielekiAnimation
	dw RegidragoAnimation
